"""Shared pipeline contracts for ingestion and preprocessing workflows."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import Enum
from pathlib import Path
from typing import Any


class PipelineDomain(str, Enum):
    """Supported pipeline domains for PHARMA-OS."""

    PATIENTS = "patients"
    TRIALS = "trials"
    ADVERSE_EVENTS = "adverse_events"
    DRUG_EXPOSURES = "drug_exposures"

    CLINICAL_NOTES = "clinical_notes"
    TRIAL_CRITERIA_DOCS = "trial_criteria_docs"
    LITERATURE_CHUNKS = "literature_chunks"


class FileFormat(str, Enum):
    """Input file formats supported by ingestion readers."""

    CSV = "csv"
    JSON = "json"
    PARQUET = "parquet"


@dataclass(slots=True)
class DataQualityIssue:
    """Single data quality issue surfaced by validation checks."""

    code: str
    message: str
    severity: str
    column: str | None = None
    row_count: int | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class ValidationReport:
    """Validation output for a single domain dataset."""

    domain: PipelineDomain
    passed: bool
    row_count: int
    required_columns: list[str]
    missing_columns: list[str] = field(default_factory=list)
    unexpected_columns: list[str] = field(default_factory=list)
    duplicate_count: int = 0
    issues: list[DataQualityIssue] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialize report into JSON-safe payload."""
        payload = asdict(self)
        payload["domain"] = self.domain.value
        return payload


@dataclass(slots=True)
class PipelineArtifact:
    """Physical output artifact generated by a pipeline stage."""

    stage: str
    domain: PipelineDomain
    path: Path
    row_count: int

    def to_dict(self) -> dict[str, Any]:
        """Serialize artifact metadata into JSON-safe payload."""
        return {
            "stage": self.stage,
            "domain": self.domain.value,
            "path": str(self.path),
            "row_count": self.row_count,
        }


@dataclass(slots=True)
class DomainPipelineResult:
    """Structured result object for a domain pipeline run."""

    domain: PipelineDomain
    run_id: str
    started_at: datetime
    finished_at: datetime
    success: bool
    validation: ValidationReport
    artifacts: list[PipelineArtifact] = field(default_factory=list)
    message: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize full domain result into JSON-safe payload."""
        return {
            "domain": self.domain.value,
            "run_id": self.run_id,
            "started_at": self.started_at.astimezone(UTC).isoformat(),
            "finished_at": self.finished_at.astimezone(UTC).isoformat(),
            "success": self.success,
            "message": self.message,
            "validation": self.validation.to_dict(),
            "artifacts": [artifact.to_dict() for artifact in self.artifacts],
        }


@dataclass(slots=True)
class PipelineRunSummary:
    """Summary object for multi-domain pipeline execution."""

    run_id: str
    started_at: datetime
    finished_at: datetime
    results: list[DomainPipelineResult]

    @property
    def succeeded_domains(self) -> int:
        return sum(1 for item in self.results if item.success)

    @property
    def failed_domains(self) -> int:
        return sum(1 for item in self.results if not item.success)

    def to_dict(self) -> dict[str, Any]:
        """Serialize run summary for metadata output."""
        return {
            "run_id": self.run_id,
            "started_at": self.started_at.astimezone(UTC).isoformat(),
            "finished_at": self.finished_at.astimezone(UTC).isoformat(),
            "succeeded_domains": self.succeeded_domains,
            "failed_domains": self.failed_domains,
            "results": [result.to_dict() for result in self.results],
        }
